-- Add extended nutrients to nutrition_goals
alter table nutrition_goals
  add column if not exists saturated_fat_g numeric,
  add column if not exists unsaturated_fat_g numeric,
  add column if not exists trans_fat_g numeric,
  add column if not exists cholesterol_mg numeric,
  add column if not exists sugar_g numeric,
  add column if not exists potassium_mg numeric,
  add column if not exists magnesium_mg numeric,
  add column if not exists phosphorus_mg numeric,
  add column if not exists zinc_mg numeric,
  add column if not exists copper_mg numeric,
  add column if not exists manganese_mg numeric,
  add column if not exists selenium_mcg numeric,
  add column if not exists iodine_mcg numeric,
  add column if not exists vitamin_a_mcg numeric,
  add column if not exists vitamin_e_mg numeric,
  add column if not exists vitamin_k_mcg numeric,
  add column if not exists vitamin_b1_mg numeric,
  add column if not exists vitamin_b2_mg numeric,
  add column if not exists vitamin_b3_mg numeric,
  add column if not exists vitamin_b5_mg numeric,
  add column if not exists vitamin_b6_mg numeric,
  add column if not exists vitamin_b7_mcg numeric,
  add column if not exists vitamin_b9_mcg numeric,
  add column if not exists vitamin_b12_mcg numeric;

-- Add extended nutrients to intake_logs
alter table intake_logs
  add column if not exists saturated_fat_g numeric,
  add column if not exists unsaturated_fat_g numeric,
  add column if not exists trans_fat_g numeric,
  add column if not exists cholesterol_mg numeric,
  add column if not exists sugar_g numeric,
  add column if not exists sodium_mg numeric,
  add column if not exists potassium_mg numeric,
  add column if not exists magnesium_mg numeric,
  add column if not exists phosphorus_mg numeric,
  add column if not exists zinc_mg numeric,
  add column if not exists copper_mg numeric,
  add column if not exists manganese_mg numeric,
  add column if not exists selenium_mcg numeric,
  add column if not exists iodine_mcg numeric,
  add column if not exists calcium_mg numeric,
  add column if not exists iron_mg numeric,
  add column if not exists vitamin_a_mcg numeric,
  add column if not exists vitamin_c_mg numeric,
  add column if not exists vitamin_d_mcg numeric,
  add column if not exists vitamin_e_mg numeric,
  add column if not exists vitamin_k_mcg numeric,
  add column if not exists vitamin_b1_mg numeric,
  add column if not exists vitamin_b2_mg numeric,
  add column if not exists vitamin_b3_mg numeric,
  add column if not exists vitamin_b5_mg numeric,
  add column if not exists vitamin_b6_mg numeric,
  add column if not exists vitamin_b7_mcg numeric,
  add column if not exists vitamin_b9_mcg numeric,
  add column if not exists vitamin_b12_mcg numeric;
